---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: "ROS_TO_GZ"  
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"  
- ros_topic_name: "/joint_states"
  gz: "/world/demo/model/diff_drive/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS" 
# - ros_topic_name: "/odom"
#   gz_topic_name: "/odom"
#   ros_type_name: "nav_msgs/msg/Odometry"
#   gz_type_name: "gz.msgs.Odometry"
#   direction: GZ_TO_ROS
# LiDAR Bridge
- ros_topic_name: "/ouster/points"    # 3D LiDAR
  gz_topic_name: "/ouster/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"   
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"  
- ros_topic_name: "/ouster/scan"    # 2D LiDAR
  gz_topic_name: "/scan/points"
  ros_type_name: "sensor_msgs/msg/LaserScan"   
  gz_type_name: "gz.msgs.LaserScan"
  direction: "GZ_TO_ROS" 
# IMU Bridge
- ros_topic_name: "/imu/out"
  gz_topic_name: "/imu/out"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS 
# Camera Bridge
- ros_topic_name: "/Cam1_front/image_raw"
  gz_topic_name: "/Cam1_front_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam1_front/camera_info"
  gz_topic_name: "/Cam1_front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam2_right/image_raw"
  gz_topic_name: "/Cam2_right_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam2_right/camera_info"
  gz_topic_name: "/Cam2_right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam3_left/image_raw"
  gz_topic_name: "/Cam3_left_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam3_left/camera_info"
  gz_topic_name: "/Cam3_left_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam4_front/image_raw"
  gz_topic_name: "/Cam4_front_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/Cam4_rear/camera_info"
  gz_topic_name: "/Cam4_rear_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"
# GNSS(NavSat) Bridge
- ros_topic_name: "/gnss1"
  gz_topic_name: "/world/my_world/model/scout_bot/link/base_link/sensor/gnss1/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/gnss2"
  gz_topic_name: "/world/my_world/model/scout_bot/link/base_link/sensor/gnss2/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: "GZ_TO_ROS"